# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: conversation_orchestrator.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'conversation_orchestrator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x63onversation_orchestrator.proto\x12\x06nvc.v1\",\n\x0bTurnRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\"\"\n\x0cTurnResponse\x12\x12\n\nai_message\x18\x01 \x01(\t2]\n\x1f\x43onversationOrchestratorService\x12:\n\x0bProcessTurn\x12\x13.nvc.v1.TurnRequest\x1a\x14.nvc.v1.TurnResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'conversation_orchestrator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TURNREQUEST']._serialized_start=43
  _globals['_TURNREQUEST']._serialized_end=87
  _globals['_TURNRESPONSE']._serialized_start=89
  _globals['_TURNRESPONSE']._serialized_end=123
  _globals['_CONVERSATIONORCHESTRATORSERVICE']._serialized_start=125
  _globals['_CONVERSATIONORCHESTRATORSERVICE']._serialized_end=218
# @@protoc_insertion_point(module_scope)
