# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: emotion_analyzer.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'emotion_analyzer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x65motion_analyzer.proto\x12\x06nvc.v1\"&\n\x16\x45motionAnalysisRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x98\x01\n\x17\x45motionAnalysisResponse\x12H\n\remotion_probs\x18\x01 \x03(\x0b\x32\x31.nvc.v1.EmotionAnalysisResponse.EmotionProbsEntry\x1a\x33\n\x11\x45motionProbsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\x32\x66\n\x16\x45motionAnalyzerService\x12L\n\x07\x41nalyze\x12\x1e.nvc.v1.EmotionAnalysisRequest\x1a\x1f.nvc.v1.EmotionAnalysisResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'emotion_analyzer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMOTIONANALYSISRESPONSE_EMOTIONPROBSENTRY']._loaded_options = None
  _globals['_EMOTIONANALYSISRESPONSE_EMOTIONPROBSENTRY']._serialized_options = b'8\001'
  _globals['_EMOTIONANALYSISREQUEST']._serialized_start=34
  _globals['_EMOTIONANALYSISREQUEST']._serialized_end=72
  _globals['_EMOTIONANALYSISRESPONSE']._serialized_start=75
  _globals['_EMOTIONANALYSISRESPONSE']._serialized_end=227
  _globals['_EMOTIONANALYSISRESPONSE_EMOTIONPROBSENTRY']._serialized_start=176
  _globals['_EMOTIONANALYSISRESPONSE_EMOTIONPROBSENTRY']._serialized_end=227
  _globals['_EMOTIONANALYZERSERVICE']._serialized_start=229
  _globals['_EMOTIONANALYZERSERVICE']._serialized_end=331
# @@protoc_insertion_point(module_scope)
