# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: empathy_generator.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'empathy_generator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x65mpathy_generator.proto\x12\x06nvc.v1\"!\n\x0fGenerateRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\")\n\x10GenerateResponse\x12\x15\n\rresponse_text\x18\x01 \x01(\t2Z\n\x17\x45mpathyGeneratorService\x12?\n\x08Generate\x12\x17.nvc.v1.GenerateRequest\x1a\x18.nvc.v1.GenerateResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'empathy_generator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GENERATEREQUEST']._serialized_start=35
  _globals['_GENERATEREQUEST']._serialized_end=68
  _globals['_GENERATERESPONSE']._serialized_start=70
  _globals['_GENERATERESPONSE']._serialized_end=111
  _globals['_EMPATHYGENERATORSERVICE']._serialized_start=113
  _globals['_EMPATHYGENERATORSERVICE']._serialized_end=203
# @@protoc_insertion_point(module_scope)
