# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nvc_processor.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'nvc_processor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13nvc_processor.proto\x12\x06nvc.v1\"!\n\x11NVCProcessRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x8e\x01\n\x12NVCProcessResponse\x12\x13\n\x0bobservation\x18\x01 \x01(\t\x12\x10\n\x08\x66\x65\x65lings\x18\x02 \x03(\t\x12\r\n\x05needs\x18\x03 \x03(\t\x12\x10\n\x08requests\x18\x04 \x03(\t\x12\x11\n\tjudgments\x18\x05 \x03(\t\x12\x1d\n\x15rewrite_nonjudgmental\x18\x06 \x01(\t2Y\n\x13NVCProcessorService\x12\x42\n\x07Process\x12\x19.nvc.v1.NVCProcessRequest\x1a\x1a.nvc.v1.NVCProcessResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nvc_processor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NVCPROCESSREQUEST']._serialized_start=31
  _globals['_NVCPROCESSREQUEST']._serialized_end=64
  _globals['_NVCPROCESSRESPONSE']._serialized_start=67
  _globals['_NVCPROCESSRESPONSE']._serialized_end=209
  _globals['_NVCPROCESSORSERVICE']._serialized_start=211
  _globals['_NVCPROCESSORSERVICE']._serialized_end=300
# @@protoc_insertion_point(module_scope)
