# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: prompt_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'prompt_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14prompt_service.proto\x12\x06nvc.v1\"#\n\x10GetPromptRequest\x12\x0f\n\x07version\x18\x01 \x01(\t\"(\n\x11GetPromptResponse\x12\x13\n\x0bprompt_text\x18\x01 \x01(\t2S\n\rPromptService\x12\x42\n\tGetPrompt\x12\x18.nvc.v1.GetPromptRequest\x1a\x19.nvc.v1.GetPromptResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'prompt_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETPROMPTREQUEST']._serialized_start=32
  _globals['_GETPROMPTREQUEST']._serialized_end=67
  _globals['_GETPROMPTRESPONSE']._serialized_start=69
  _globals['_GETPROMPTRESPONSE']._serialized_end=109
  _globals['_PROMPTSERVICE']._serialized_start=111
  _globals['_PROMPTSERVICE']._serialized_end=194
# @@protoc_insertion_point(module_scope)
